 # Copyright (c) 2023, pjlab.
 # All rights reserved.


datasets: 
  cap3d_captioning3d: # name of the dataset builder
    dataset_card: dataset_card/cap3d_captioning3d.md
    # data_dir: ${env.data_dir}/datasets
    # data_type: images # [images|videos|features]
    data_type: [points]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: data/cap3d/annotations/cap3d_caption_train.json
          storage: cap3d/annotations/cap3d_caption_train.json
        val:
          url: data/cap3d/annotations/cap3d_caption_val.json
          storage: cap3d/annotations/cap3d_caption_val.json
        test:
          url: data/cap3d/annotations/val_and_test/cap3d_real_and_chatgpt_caption_test.json
          storage: cap3d/annotations/val_and_test/cap3d_real_and_chatgpt_caption_test.json
      points:
        storage: cap3d/points/Cap3D_pcs_8192_xyz_w_color/


        

